server.port=8080
spring.thymeleaf.cache=false
logging.level.org.springframework=INFO
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=replayGroup
management.endpoints.web.exposure.include=*